name: UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Check github.workspace
        run: echo ${{github.workspace}}

      # Build the project
      - name: Build
        run: dotnet build
      
      # Install Playwright browsers
      - name: Ensure browsers are installed
        run: pwsh ${{github.workspace}}/tests/Library.Tests.Ui/bin/Debug/net8.0/playwright.ps1 install --with-deps
        
      # Run NUnit Playwright tests
      - name: Run UI tests
        run: dotnet test ${{github.workspace}}/tests/Library.Tests.Ui/Library.Tests.Ui.csproj --logger "trx;LogFileName=test-results.trx" --results-directory ${{github.workspace}}tests/Library.Tests.Ui/bin/Debug/net8.0/test-results
        
      # Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{github.workspace}}/tests/Library.Tests.Ui/bin/Debug/net8.0/test-results

      # Display test results using dorny/test-reporter
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # Always run this step, even if previous steps fail
        with:
          artifact: test-results
          reporter: dotnet-trx
          path: 'test-results/test-results.trx'
          name: test-results.trx
          list-tests: 'all'
          fail-on-error: 'false'